codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "1...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        flags: 
          - unit
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes