codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "1...100"
  
  status:
    project:
      default:
        target: 15%  # Realistic given current 9.96% coverage
        threshold: 2%  # Allow 2% variance
        base: auto
        flags: 
          - unit
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 30%  # More realistic for new code
        threshold: 10%  # Allow more variance for patches
        base: auto
        informational: true  # Make it non-blocking

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "src/alpha_pulse/tests/**"  # Don't count test files in coverage
  - "**/__pycache__/**"
  - "**/migrations/**"
  - "src/alpha_pulse/api/main.py:startup_event"  # Hard to test startup
  - "src/alpha_pulse/api/main.py:shutdown_event"  # Hard to test shutdown