version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: alphapulse-timescaledb
    environment:
      POSTGRES_DB: alphapulse
      POSTGRES_USER: alphapulse
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alphapulse"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - alphapulse-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: alphapulse-redis
    command: redis-server --requirepass password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - alphapulse-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: alphapulse-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@alphapulse.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - alphapulse-network
    restart: unless-stopped

networks:
  alphapulse-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
