# Grid Hedging Strategy Configuration

# Trading parameters
symbol: BTCUSDT
trading_mode: PAPER  # REAL, PAPER, or RECOMMENDATION

# Grid parameters
grid:
  volatility: 0.02  # 2% daily volatility
  num_levels: 5     # Number of grid levels
  direction: SHORT  # For hedging spot positions
  rebalance_interval: 60  # Seconds between grid rebalances

# Risk management
risk:
  stop_loss_pct: 0.04    # 4% stop loss (2 standard deviations)
  take_profit_pct: 0.06  # 6% take profit (1.5x stop loss)
  max_position_size: 1.0  # Maximum position size in BTC
  max_drawdown_pct: 0.25  # Maximum allowed drawdown

# Position sizing
position:
  target_volatility: 0.01  # 1% daily target volatility
  max_size_pct: 0.20      # Maximum 20% of portfolio per grid level
  volatility_lookback: 20  # Days for volatility calculation

# Risk analysis
risk_analysis:
  rolling_window: 20    # Days for risk metrics
  var_confidence: 0.95  # VaR confidence level
  mc_simulations: 10000 # Monte Carlo simulations

# Exchange settings
exchange:
  name: binance  # or bybit
  testnet: true  # Use testnet for safety
  credentials:
    # These should be set via environment variables
    api_key: ${EXCHANGE_API_KEY}
    api_secret: ${EXCHANGE_API_SECRET}

# Logging
logging:
  level: INFO
  rotation: "1 day"
  format: "{time} | {level} | {message}"