apiVersion: v1
kind: Service
metadata:
  name: {{ include "alphapulse.fullname" . }}-api
  labels:
    {{- include "alphapulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "alphapulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
