apiVersion: v1
kind: Secret
metadata:
  name: alphapulse-secrets
  labels:
    {{- include "alphapulse.labels" . | nindent 4 }}
type: Opaque
data:
  # These should be set via --set-file or external secrets manager (e.g., AWS Secrets Manager, Vault)
  # DO NOT commit actual secrets to git
  database-url: ""  # Base64 encoded PostgreSQL connection string
  redis-password: ""  # Base64 encoded Redis password
  postgres-password: ""  # Base64 encoded PostgreSQL password
  jwt-secret: ""  # Base64 encoded JWT secret key
  openai-api-key: ""  # Base64 encoded OpenAI API key
  exchange-api-key: ""  # Base64 encoded exchange API key
  exchange-api-secret: ""  # Base64 encoded exchange API secret
