# AlphaPulse Kubernetes Secrets Configuration
# 
# This file contains templates for Kubernetes secrets.
# DO NOT commit actual secrets to version control!
# 
# Usage:
# 1. Copy this file to secrets-prod.yaml
# 2. Replace all placeholder values with actual secrets
# 3. Apply with: kubectl apply -f secrets-prod.yaml

apiVersion: v1
kind: Secret
metadata:
  name: alphapulse-database
  namespace: alphapulse
type: Opaque
stringData:
  host: "your-database-host"
  port: "5432"
  database: "alphapulse"
  username: "your-database-username"
  password: "your-database-password"

---

apiVersion: v1
kind: Secret
metadata:
  name: alphapulse-security
  namespace: alphapulse
type: Opaque
stringData:
  jwt-secret: "your-very-long-random-jwt-secret-here"
  encryption-key: "your-32-byte-encryption-key-here"

---

apiVersion: v1
kind: Secret
metadata:
  name: alphapulse-exchanges
  namespace: alphapulse
type: Opaque
stringData:
  # Binance
  binance-api-key: "your-binance-api-key"
  binance-api-secret: "your-binance-api-secret"
  
  # Bybit
  bybit-api-key: "your-bybit-api-key"
  bybit-api-secret: "your-bybit-api-secret"
  
  # Coinbase
  coinbase-api-key: "your-coinbase-api-key"
  coinbase-api-secret: "your-coinbase-api-secret"
  coinbase-passphrase: "your-coinbase-passphrase"

---

apiVersion: v1
kind: Secret
metadata:
  name: alphapulse-data-providers
  namespace: alphapulse
type: Opaque
stringData:
  iex-cloud-api-key: "your-iex-cloud-api-key"
  polygon-api-key: "your-polygon-api-key"
  alpha-vantage-api-key: "your-alpha-vantage-api-key"
  finnhub-api-key: "your-finnhub-api-key"

---

# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: alphapulse-config
  namespace: alphapulse
data:
  ALPHAPULSE_ENV: "production"
  ALPHAPULSE_LOG_LEVEL: "INFO"
  ALPHAPULSE_API_HOST: "0.0.0.0"
  ALPHAPULSE_API_PORT: "8000"
  ALPHAPULSE_MAX_POSITIONS: "10"
  ALPHAPULSE_RISK_PER_TRADE: "0.02"
  ALPHAPULSE_MAX_LEVERAGE: "1.0"

---

# Service Account for AWS Secrets Manager access (if using IRSA)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alphapulse-secrets-manager
  namespace: alphapulse
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT_ID:role/AlphaPulseSecretsManagerRole

---

# Example Deployment using the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphapulse-api
  namespace: alphapulse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alphapulse-api
  template:
    metadata:
      labels:
        app: alphapulse-api
    spec:
      serviceAccountName: alphapulse-secrets-manager
      containers:
      - name: alphapulse
        image: alphapulse:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: alphapulse-config
        env:
        # Database secrets
        - name: ALPHAPULSE_DB_HOST
          valueFrom:
            secretKeyRef:
              name: alphapulse-database
              key: host
        - name: ALPHAPULSE_DB_PORT
          valueFrom:
            secretKeyRef:
              name: alphapulse-database
              key: port
        - name: ALPHAPULSE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: alphapulse-database
              key: database
        - name: ALPHAPULSE_DB_USER
          valueFrom:
            secretKeyRef:
              name: alphapulse-database
              key: username
        - name: ALPHAPULSE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alphapulse-database
              key: password
        
        # Security secrets
        - name: ALPHAPULSE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: alphapulse-security
              key: jwt-secret
        - name: ALPHAPULSE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: alphapulse-security
              key: encryption-key
        
        # Exchange credentials
        - name: ALPHAPULSE_BINANCE_API_KEY
          valueFrom:
            secretKeyRef:
              name: alphapulse-exchanges
              key: binance-api-key
        - name: ALPHAPULSE_BINANCE_API_SECRET
          valueFrom:
            secretKeyRef:
              name: alphapulse-exchanges
              key: binance-api-secret
        
        # Add more environment variables as needed...
        
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5