# AI Hedge Fund Configuration

# Trading Configuration
trading:
  symbols:
    - "BTCUSDT"
    - "ETHUSDT"
    - "BNBUSDT"
    - "ADAUSDT"
    - "SOLUSDT"
  base_currency: "USDT"
  min_trade_value: 100.0
  execution_style: "market"
  max_slippage: 0.002  # 0.2%

# Agent Configuration
agents:
  agent_weights:
    activist: 0.15    # Bill Ackman style
    value: 0.20       # Warren Buffett style
    fundamental: 0.20 # Company analysis
    sentiment: 0.15   # Market sentiment
    technical: 0.15   # Technical analysis
    valuation: 0.15   # Price evaluation
  
  agent_configs:
    activist:
      min_confidence: 0.7
      lookback_period: 90
      
    value:
      min_confidence: 0.7
      lookback_period: 180
      
    fundamental:
      min_confidence: 0.6
      lookback_period: 90
      metrics:
        - "market_cap"
        - "pe_ratio"
        - "revenue_growth"
        - "profit_margin"
        
    sentiment:
      min_confidence: 0.6
      lookback_period: 30
      sources:
        - "news"
        - "social_media"
        - "market_sentiment"
        
    technical:
      min_confidence: 0.6
      lookback_period: 90
      indicators:
        - "rsi"
        - "macd"
        - "bollinger_bands"
        - "moving_averages"
        
    valuation:
      min_confidence: 0.7
      lookback_period: 90
      metrics:
        - "price_to_book"
        - "enterprise_value"
        - "dcf_valuation"

# Risk Management Configuration
risk_management:
  max_position_size: 0.2      # Maximum 20% in single position
  max_portfolio_leverage: 1.5  # Maximum 150% exposure
  max_drawdown: 0.25          # Maximum 25% drawdown
  stop_loss: 0.1              # 10% stop loss
  var_confidence: 0.95        # 95% VaR confidence
  risk_free_rate: 0.0         # Risk-free rate
  target_volatility: 0.15     # Target annual volatility
  rebalance_threshold: 0.1    # 10% threshold for rebalancing
  initial_portfolio_value: 1000000.0  # $1M initial capital

  position_sizing:
    method: "adaptive"
    volatility_scaling: true
    min_position_value: 1000.0
    max_position_value: 200000.0

  risk_limits:
    sector_exposure: 0.4      # Max 40% per sector
    asset_correlation: 0.7    # Max 70% correlation
    beta_exposure: 1.5        # Max 150% beta exposure
    var_limit: 0.02          # 2% daily VaR limit

# Portfolio Management Configuration
portfolio_management:
  strategy: "hierarchical_risk_parity"  # Default strategy
  rebalancing_frequency: "daily"
  min_trade_spacing: 3600  # Minimum 1 hour between trades
  
  optimization:
    target_return: 0.20       # 20% annual target
    risk_aversion: 0.5        # Risk aversion parameter
    min_weight: 0.05         # Minimum position weight
    max_weight: 0.4          # Maximum position weight

  constraints:
    min_assets: 3            # Minimum number of assets
    max_assets: 10           # Maximum number of assets
    turnover_limit: 0.1      # Maximum 10% daily turnover

# Monitoring Configuration
monitoring:
  metrics:
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "var_95"
    - "expected_shortfall"
    - "tracking_error"
    - "information_ratio"
    - "calmar_ratio"
    
  alerts:
    drawdown_warning: 0.15    # Alert at 15% drawdown
    var_breach: 0.03         # Alert at 3% VaR
    exposure_warning: 1.3     # Alert at 130% exposure
    
  reporting:
    frequency: "daily"
    include_trades: true
    include_metrics: true
    include_positions: true
    save_reports: true

# LLM Integration Configuration
llm:
  enabled: true
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 1000
  
  analysis:
    frequency: "daily"
    include_news: true
    include_sentiment: true
    include_fundamentals: true
    
  tasks:
    - "portfolio_analysis"
    - "risk_assessment"
    - "market_analysis"
    - "strategy_recommendation"