# Data Pipeline Configuration

# Market Data Provider (Binance)
market_data:
  binance:  # Added this nesting level
    provider: "binance"
    api_key: "${BINANCE_API_KEY}"
    api_secret: "${BINANCE_API_SECRET}"
    testnet: false  # Changed to use real API
    cache_ttl: 300  # 5 minutes

# Fundamental Data Provider (Alpha Vantage)
fundamental_data:
  alpha_vantage:  # Added this nesting level
    provider: "alpha_vantage"
    api_key: "${ALPHA_VANTAGE_API_KEY}"
    cache_ttl: 3600  # 1 hour

# Sentiment Data Provider (Finnhub)
sentiment_data:
  finnhub:  # Added this nesting level
    provider: "finnhub"
    api_key: "${FINNHUB_API_KEY}"
    cache_ttl: 300  # 5 minutes
    news_lookback_days: 7
    social_lookback_hours: 24

# Technical Analysis Provider (TA-Lib)
technical_analysis:
  provider: "talib"
  max_workers: 4

# General Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

cache:
  enabled: true
  backend: "memory"
  default_ttl: 300  # 5 minutes

error_handling:
  max_retries: 3
  retry_delay: 1.0  # seconds
  exponential_backoff: true

rate_limiting:
  enabled: true
  requests_per_minute: 60
  burst_size: 10

# Connection Settings
connection:
  request_timeout: 30  # seconds
  tcp_connector_limit: 100  # maximum concurrent connections