# PPO Trend Following Strategy Configuration

# Environment Configuration
environment:
  initial_capital: 100000.0
  commission: 0.001
  position_size: 0.3  # Increased position sizing for more trade opportunities
  window_size: 20    # Reduced window for faster signal generation
  reward_scaling: 5.0
  risk_aversion: 0.01  # Lower risk aversion to encourage trading
  max_position: 5.0  # Increased max position for more flexibility
  stop_loss_pct: 0.1   # Wider stop-loss to avoid premature exits
  take_profit_pct: 0.2 # Higher take profit for better reward/risk

# Neural Network Configuration
network:
  hidden_sizes: [256, 128, 64]  # Deep network for pattern recognition
  activation_fn: "relu"
  use_lstm: true               # LSTM for temporal pattern detection
  lstm_units: 128
  attention_heads: 4           # Multi-head attention for trend detection
  dropout_rate: 0.1

# Training Configuration
training:
  total_timesteps: 200000  # More training steps
  learning_rate: 0.0003   # Higher learning rate for faster adaptation
  batch_size: 512        # Larger batch size for better gradient estimates
  n_steps: 512          # Shorter steps for more frequent updates
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.3       # Wider clip range for more exploration
  ent_coef: 0.05       # Higher entropy to encourage exploration
  vf_coef: 0.5
  max_grad_norm: 0.5
  eval_freq: 10000     # More frequent evaluation
  n_eval_episodes: 10  # More evaluation episodes
  checkpoint_freq: 10000
  n_envs: 4           # More parallel environments
  device: "auto"
  cuda_deterministic: true
  precision: "float32"

# Data Configuration
data:
  symbol: "BTCUSDT"  # Default to BTC for crypto trend following
  eval_split: 0.2
  feature_engineering:
    # Technical indicators for trend detection
    moving_averages: [20, 50, 200]  # Multiple timeframe trend analysis
    momentum_indicators: ["rsi", "macd", "adx"]  # Trend strength indicators
    volatility_indicators: ["atr", "bbands"]     # Volatility for position sizing
    volume_indicators: ["obv", "vwap"]           # Volume confirmation