name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: alphapulse_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/alphapulse_test
      REDIS_URL: redis://localhost:6379
      EXCHANGE_API_KEY: test-api-key
      EXCHANGE_API_SECRET: test-api-secret
      OPENAI_API_KEY: test-openai-key
      ENVIRONMENT: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libpq-dev \
          libffi-dev \
          libssl-dev \
          redis-tools \
          postgresql-client
    
    - name: Set up Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Show Package Structure
      run: |
        # Show directory structure for debugging
        echo "Package structure:"
        ls -R src/alpha_pulse/
    
    # Install TA-Lib C library v0.6.4 from .deb package
    - name: Install TA-Lib C library v0.6.4
      run: |
        echo "===== Installing TA-Lib C library v0.6.4 from .deb ====="
        # Install dependencies for dpkg if needed (like wget)
        sudo apt-get update
        sudo apt-get install -y wget

        # Download and install TA-Lib C library v0.6.4 .deb
        wget https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib_0.6.4_amd64.deb -O ta-lib_0.6.4_amd64.deb
        sudo dpkg -i ta-lib_0.6.4_amd64.deb
        # Install any missing dependencies for the installed .deb
        sudo apt-get install -f -y

        echo "TA-Lib C library v0.6.4 installation completed via .deb"
    
    # Install Python dependencies with Poetry
    - name: Install dependencies with Poetry
      run: |
        echo "===== Installing Python dependencies with Poetry ====="
        
        # Increase pip timeout for large packages like Ray/Dask
        export PIP_DEFAULT_TIMEOUT=120
        
        # Install with no interaction and include dev dependencies for testing
        poetry install --no-interaction --no-ansi
        
        # Verify the TA-Lib installation
        echo "Verifying TA-Lib installation..."
        poetry run python -c "import talib; print(f'TA-Lib version: {talib.__version__}'); print(f'Available functions: {dir(talib)[:5]}...')" || echo "Failed to import talib"
        
        # Verify the specific function that uses the missing symbol
        echo "Verifying TA-Lib AVGDEV function..."
        poetry run python -c "import talib; import numpy as np; data = np.random.random(100); result = talib.AVGDEV(data, timeperiod=5); print('AVGDEV function works!')" || echo "Failed to use AVGDEV function"
    
    - name: Verify dependencies
      run: |
        echo "===== Verifying Python dependencies ====="
        
        # Verify core package imports
        echo "Verifying core package imports..."
        poetry run python -c "import alpha_pulse; print(f'AlphaPulse version: {alpha_pulse.__version__}')"
        
        # Verify key dependencies are installed
        echo "Verifying key dependencies..."
        poetry run python -c "
import sys
dependencies = ['httpx', 'ccxt', 'langchain_openai', 'textblob', 'loguru', 'fastapi', 'sqlalchemy', 'psycopg2', 'redis']
failed = []
for dep in dependencies:
    try:
        __import__(dep)
        print(f'✓ {dep}')
    except ImportError as e:
        print(f'✗ {dep}: {e}')
        failed.append(dep)
if failed:
    print(f'Failed to import: {failed}')
    sys.exit(1)
print('All key dependencies verified!')
"
    
    - name: Initialize test database
      run: |
        echo "===== Initializing test database ====="
        
        # Wait for PostgreSQL to be ready
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        
        # Test Redis connection
        redis-cli -h localhost -p 6379 ping
        
        echo "Services are ready!"
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 src/alpha_pulse --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        poetry run flake8 src/alpha_pulse --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        # Show test directory structure
        echo "Test directory structure:"
        ls -R src/alpha_pulse/tests/
        
        # Run basic import tests first to verify CI setup
        echo "Running basic import tests..."
        timeout 300 poetry run pytest \
          --cov=src/alpha_pulse \
          --cov-report=xml \
          --cov-report=term-missing \
          -v \
          --tb=short \
          --timeout=60 \
          src/alpha_pulse/tests/test_basic_imports.py
        
        # Check if pytest found any tests
        if [ $? -eq 5 ]; then
          echo "No tests were collected - this might indicate a configuration issue"
          exit 1
        fi
        
        echo "Basic tests completed successfully!"
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: blackms/AlphaPulse