name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
      EXCHANGE_API_SECRET: ${{ secrets.EXCHANGE_API_SECRET }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.11"
        channels: conda-forge,defaults
        channel-priority: strict
        activate-environment: test-env
    
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Install TA-Lib from conda-forge
        conda install -c conda-forge ta-lib
        
        # Upgrade pip and install base tools
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov pytest-asyncio
        
        # Install RL dependencies
        pip install stable-baselines3[extra]
        
        # Install the package in editable mode
        pip install -e .
        
        # Debug: Show package structure
        echo "Package structure:"
        ls -R src/alpha_pulse/
    
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/alpha_pulse --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 src/alpha_pulse --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        # Show test directory structure
        echo "Test directory structure:"
        ls -R src/alpha_pulse/tests/
        
        # Run tests
        pytest -v
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}