name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
      EXCHANGE_API_SECRET: ${{ secrets.EXCHANGE_API_SECRET }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install system dependencies and TA-Lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        # Download and install TA-Lib
        cd /tmp
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
        rm -rf ta-lib ta-lib-0.4.0-src.tar.gz
        # Verify installation
        ls -l /usr/lib/libta_lib*
        sudo ldconfig
        pkg-config --libs ta-lib
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # Install TA-Lib Python wrapper
        pip install numpy
        pip install TA-Lib
        # Install the package in editable mode with dev dependencies
        pip install -e ".[dev]"
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/alpha_pulse --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 src/alpha_pulse --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
