name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
      EXCHANGE_API_SECRET: ${{ secrets.EXCHANGE_API_SECRET }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.11"
        channels: conda-forge,defaults
        channel-priority: strict
        activate-environment: test-env
    
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Install TA-Lib from conda-forge
        conda install -c conda-forge ta-lib
        
        # Upgrade pip and install base tools
        python -m pip install --upgrade pip
        pip install flake8
        pip install numpy
        
        # Install RL dependencies
        pip install stable-baselines3
        
        # Ensure package structure exists
        mkdir -p src/alpha_pulse/models
        
        # Create necessary __init__.py files if they don't exist
        touch src/alpha_pulse/__init__.py
        touch src/alpha_pulse/models/__init__.py
        
        # Copy basic_models.py if it doesn't exist
        if [ ! -f src/alpha_pulse/models/basic_models.py ]; then
          echo "Creating basic_models.py..."
          cp src/alpha_pulse/models/basic_models.py.template src/alpha_pulse/models/basic_models.py || true
        fi
        
        # Install the package in editable mode with dev dependencies
        pip install -e ".[dev]"
        
        # Verify package structure
        python -c "from alpha_pulse.models.basic_models import ModelTrainer; print('ModelTrainer found')"
    
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/alpha_pulse --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 src/alpha_pulse --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        # Run tests with verbose output and show local variables on failures
        pytest -v --showlocals
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}